<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="cisummarizer.PmdProblemCollectorErrorTest" tests="5" skipped="0" failures="0" errors="0" timestamp="2020-08-12T23:15:00" hostname="LAPTOP-631HSM73" time="0.048">
  <properties/>
  <testcase name="it_should_have_no_problems_but_have_errors_when_given_a_path_to_bad_file(String)[1]" classname="cisummarizer.PmdProblemCollectorErrorTest" time="0.008"/>
  <testcase name="it_should_have_no_problems_but_have_errors_when_given_a_path_to_bad_file(String)[2]" classname="cisummarizer.PmdProblemCollectorErrorTest" time="0.005"/>
  <testcase name="it_should_have_no_problems_but_have_errors_when_given_a_path_to_bad_file(String)[3]" classname="cisummarizer.PmdProblemCollectorErrorTest" time="0.017"/>
  <testcase name="it_should_have_no_problems_but_have_errors_when_given_a_path_to_bad_file(String)[4]" classname="cisummarizer.PmdProblemCollectorErrorTest" time="0.011"/>
  <testcase name="forInfinitest()" classname="cisummarizer.PmdProblemCollectorErrorTest" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[something went south with src\test\resources\pmd-problem-collector\blorp
   here is the exception: java.nio.file.NoSuchFileException: src\test\resources\pmd-problem-collector\blorp
something went south with src\test\resources\pmd-problem-collector\empty.xml
   here is the exception: java.nio.file.NoSuchFileException: src\test\resources\pmd-problem-collector\empty.xml
[Fatal Error] :1:1: Content is not allowed in prolog.
something went south with src\test\resources\pmd-problem-collector\malformed.xml
   here is the exception: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
]]></system-err>
</testsuite>
